### ISSUE TITLE
Make iPhone App

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#263]
Use Apple Developer to write an app for the App Store.

MVP:
- [x] App launches a browser to get to 3Scape.me
(Better if app embeds browser)
- [x] App displays user profile & prefs

**Comment by popcatalin118** [comment]
officially able to grab users information,app is able to launch in browser, still fixing the notification issue. I have set up sign up for user profile as well

**Comment by kmcurry** [comment]
:+1: Can you post a screen capture?

**Comment by popcatalin118** [comment]
embedded browsing works and fixed notification issue from embedded browsing

**Comment by kmcurry** [comment]
Let me close issues :^)
