### ISSUE TITLE
Create Display Area Reference Specification

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#283]
We need reference specs for available screen space.

[Example](https://docs.google.com/a/3scape.me/drawings/d/1pfB3uNsFTskY0beDdWKZq7GgKwY7wsOQUUyINPGltto/edit)

**Comment by kmcurry** [comment]
https://drive.google.com/file/d/0B9aAGmd9iudham8tQnVwckNBRDg/view?usp=sharing

**Comment by kmcurry** [comment]
Do we need to elaborate to account for when the browser is in full screen mode and when it isn't? I'm on the fence about how helpful it will be.

**Comment by herogerik** [comment]
That would be helpful yes. How big the size of the viewport 3Scape is being
seen at should change its layout to accommodate.
