### ISSUE TITLE
Sometimes the model doesn't go where I want

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#315]
When I first load 3Scape I click a point on the Grid where I want to load a model. Sometimes the model loads instead at 0,0,0.

Check initializations based on pointWorld in 3Scape.

![screen shot 2015-02-24 at 1 01 06 am](https://cloud.githubusercontent.com/assets/69151/6344052/b6a86f42-bbc0-11e4-994d-51ecfc601585.png)

**Comment by katlandreth** [comment]
Similar Issue as above - 

Unexpected Behavior -

    Load a new 3Scape
    Without clicking on the canvas, click an object button from the toolbar
    Sometimes the object gets created below the texture plane and keeps falling forever

Expected Behavior -

    Load a new 3Scape
    Without clicking on the canvas, click an object button from the toolbar
    Object will be placed on top of the texture plane in the middle of the users current view

Video: https://www.dropbox.com/s/ejd4ekn97nwmw5t/NewObjectCreatedBelowPlane.mov?dl=0
