### ISSUE TITLE
Make dropdown menu pretty

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#324]
As coded:
![screen shot 2015-02-26 at 7 22 49 am](https://cloud.githubusercontent.com/assets/69151/6391832/7045ed1c-bd88-11e4-8833-62f0506fcbdd.png)

Mockup:
![screen shot 2015-02-26 at 7 29 14 am](https://cloud.githubusercontent.com/assets/69151/6391917/5bf24b48-bd89-11e4-8cf6-ff135b9bb846.png)

**Comment by jperez757** [comment]
#360 ties in with this a little I think as far as the "Load Saved 3Scape" header is concerned. I left notes at #360 about it.
