### ISSUE TITLE
Weirdness with AnimalMover & Selection?

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#326]
There's something odd going on with AnimalMover and selection in 3Scape.

1. I load a model, ex., Pyramid.
2. I add an AnimalMover to the Pyramid with the Bolt button on the context menu.
3. If the Pyramid is not selected it mostly spins in circles, advancing very extremely little.
4. When I select the Pyramid it roams and wanders as I expect.
5. When the Pyramid that's roaming has its context menu brought up, it flies/floats above the texture plane in an upward trajectory. Deselecting makes the Pyramid fall to the texture plane again.

**Comment by katlandreth** [comment]
Clarification on point 5 - This is happening when the pyramid has been rotated. If it's rotated using the up or down buttons in the context menu, part of the pyramid will sink below the texture plane. Sometimes making it wander will cause it to completely fall below the texture plane. Other times it wanders partially submerged in the plane, but will start to fly when selected.
