### ISSUE TITLE
Unexpected Scaling and Rotation with Trackpad Gestures

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#329]
I’m getting weird scaling and rotation behavior when using trackpad on my mac. It's inconsistent, but here are some steps that will sometimes recreate the issue:

* Place a Pyramid on the texture plane
* Open the Pyramid's context menu
* Rotate the Pyramid a few increments using the counter-clockwise rotation button (or make another adjustment)
* Move the cursor up and down, or diagonally back and forth across the object - not click-dragging but hovering
* The Pyramid will scale up and down slightly as you move the cursor back and forth

https://www.dropbox.com/s/gpqrcowrb7i317n/ScalingOnTrackpad.mov?dl=0  Link to a video of this happening - the steps above were followed. Deselecting the shape or making another adjustment makes the effect stop.

PS: I'm using FireFox 36.0, Macbook Pro Retina with iOS 10.10.2 (Yosemite)

**Comment by kmcurry** [comment]
Was issue with context menu event capture. Context menu no longer exists.
