### ISSUE TITLE
Inconsistent Panning with Mouse

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#330]
Most of the time when I click and drag the 3Scape when an object is not selected, the camera rotates around the canvas. But, sometimes when I click and drag the 3Scape, the camera view pans up, down, left, and right. 

Link to Video:  https://www.dropbox.com/s/rhjj6cg3suddka8/InconsistentPanning.mov?dl=0

Using the arrow keys makes the camera rotate as expected, but click/dragging behavior changes in this video.

**Comment by kmcurry** [comment]
Was an issue with context menu, which is now disabled on the canvas.
