### ISSUE TITLE
Delete (Backspace) Key Should Delete Selected Object

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#335]
If I select an object in 3Scape, and hit the delete key, the object should be deleted. Right now delete key triggers the default browser behavior which is to go back a page. This is frustrating and unexpected especially in context.

When an object is deleted a message should appear letting them know that the deletion was successful and they can undo the delete action if they want. (Reasoning and example here :https://www.goodui.org/#8). This message could go away when the user takes any other action (like the verification and undo option when you delete an email in gmail).

I think the default behavior of navigating back should be disabled when when an object is not selected. Instead, we could show an error message asking if they meant to delete an object (in which case select the object first then hit delete) or if they meant to delete the 3Scape (in which case that button is in the Menu dropdown), or if they meant to go back a page (in which case hold ALT plus the left arrow key). 

The error message should be non-blocking (user should not have to verify or click anything in the message to continue using 3Scape) and it should disappear after a set interval.

Reference to other UXers who dislike this delete key action and how to disable it: http://ux.stackexchange.com/questions/53176/why-does-backspace-go-back-a-page-this-behavior-is-so-frustrating

**Comment by katlandreth** [comment]
Delete is making the browser go back again instead of deleting the selected shape.

**Comment by kmcurry** [comment]
Dangit. Thought I fixed this.


On Mon, Mar 9, 2015 at 3:02 PM, katlandreth <notifications@github.com>
wrote:

> Delete is making the browser go back again instead of deleting the
> selected shape.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmcurry/3Scape/issues/335#issuecomment-77919837>.
>



-- 
Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me

**Comment by katlandreth** [comment]
I thought it was fixed too - but I just started having a problem with it again today.

**Comment by kmcurry** [comment]
Model.onRemove is throwing an error in BwJS. That's probably messing it up. @mbraz003 is looking into the model remove error.

**Comment by kmcurry** [comment]
That was it. All better again.
