### ISSUE TITLE
New Object Gets Placed Below Texture Plane

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#340]
Unexpected Behavior -
* Load a new 3Scape
* Without clicking on the canvas, click an object button from the toolbar
* Sometimes the object gets created below the texture plane and keeps falling forever

Expected Behavior -
* Load a new 3Scape
* Without clicking on the canvas, click an object button from the toolbar
* Object will be placed on top of the texture plane in the middle of the users current view

Video: https://www.dropbox.com/s/ejd4ekn97nwmw5t/NewObjectCreatedBelowPlane.mov?dl=0

**Comment by kmcurry** [comment]
Duplicates #315. Combine and de-dupe by labeling one of the issues with "duplicate" label and closing the issue.
