### ISSUE TITLE
Sometimes I Can't Select a Model

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#341]
Unexpected Behavior -
* I click on a model, but I can't select it
* I drag the canvas to reorient the camera and click on the model again
* After reorienting, I can select the object

Expected Behavior -
* When I click on a model it is selected with a yellow outline around it

Video:  https://www.dropbox.com/s/a6urwg7b73wuodn/ShapeFloatsWhenScaled.mov?dl=0 you can see me struggling with this at the beginning of the video

**Comment by kmcurry** [comment]
Do you get the hand cursor when this happens? I'm pretty sure this bug is
the context menu getting in the way. Fixable.

On Monday, March 2, 2015, katlandreth <notifications@github.com> wrote:

> Unexpected Behavior -
>
>    - I click on a model, but I can't select it
>    - I drag the canvas to reorient the camera and click on the model again
>    - After reorienting, I can select the object
>
> Expected Behavior -
>
>    - When I click on a model it is selected with a yellow outline around
>    it
>
> Video:
> https://www.dropbox.com/s/a6urwg7b73wuodn/ShapeFloatsWhenScaled.mov?dl=0
> you can see me struggling with this at the beginning of the video
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmcurry/3Scape/issues/341>.
>


-- 
Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me

**Comment by katlandreth** [comment]
Yep - hand cursor.
