### ISSUE TITLE
Arrow Keys Stop Working When Rotating Object

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#342]
Related to Issue #343 and #344 

Unexpected Behavior - 
* Place an Object, and open its context menu
* Use the arrow keys to rotate the object
* At some point, the arrow keys stop working on the object and will scroll the canvas up and down instead

Expected Behavior -
* Place an Object, and open its context menu
* Use the arrow keys to rotate the object
* Arrow Keys continue to rotate the object as long as the context menu is open

**Comment by kmcurry** [comment]
This UI/UX was changed so the issue is no longer valid.
