### ISSUE TITLE
Arrow Keys Not Rotating Selected Object

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#343]
Related to Issues #342 and #344 

Unexpected Behavior -
* Select an object and use press arrow keys on the keyboard, object doesn't rotate
* Select object, and drag it into the air
* Press arrow keys again and object rotates properly

Expected Behavior - 
* When an object is selected, arrow keys rotate the object

Video:  https://www.dropbox.com/s/yp2u1w0cbvdmf17/ArrowKeys.mov?dl=0 First I select the object and use the arrow keys but they cause scrolling behavior. Then I drag the object up and use arrow keys and object rotates.

**Comment by kmcurry** [comment]
Should they arrows _rotate_ or _move_?

I put the code back in that makes the arrow keys work. But we had them set to move, not rotate.

**Comment by katlandreth** [comment]
I'm not sure which they should do - but I find myself wanting them to nudge instead of rotate.

**Comment by kmcurry** [comment]
It's in there now as move. Try it out

On Wednesday, March 4, 2015, katlandreth <notifications@github.com> wrote:

> I'm not sure which they should do - but I find myself wanting them to
> nudge instead of rotate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmcurry/3Scape/issues/343#issuecomment-77162607>.
>


-- 
Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me

**Comment by katlandreth** [comment]
Awesome! It works exactly as I would expect when the camera is at it's original position. Would be extra cool if you're always using up arrow for forward, down arrow for backward, left arrow for left, and right arrow for right. Right now the keys seems to be mapped onto cardinal directions which is a little confusing if you rotate the camera. If you rotate the camera around 180 degrees, up arrow moves the shape backwards etc.
