### ISSUE TITLE
Arrow Keys Not Rotating Proper Direction

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#344]
Related to Issue #342 and #343 

Unexpected Behavior -
* Select Object and use arrow keys to rotate (as per issue #343 you have to drag the object into the air first)
* Arrow keys only rotate in two directions instead of 4 (Up and Right arrows do the same thing, Down and Left arrows do the same thing).

Expected Behavior -
* Arrow keys should rotate the object in 4 different directions

Video: https://www.dropbox.com/s/yp2u1w0cbvdmf17/ArrowKeys.mov?dl=0  When the object is successfully rotated, I'm using all 4 arrow keys but it's only rotating in 2 directions.

**Comment by kmcurry** [comment]
We're using the arrow keys for movement. Movement is now view-relative, which means that left is always left on the screen and right is always right.
