### ISSUE TITLE
Panning Action Gets Stuck in One Direction

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#348]
Sometimes the mouse panning action gets stuck in a state where dragging the mouse in any direction causes the texture plane to flip end over end. 

Video: https://www.dropbox.com/s/wg8ktyaywglq98j/PanningMouseFlipsCanvas.mov?dl=0

In the video above, even though I'm moving my mouse left, right, up, and down, the texture plane is only moving in one direction (or the camera is only moving in one direction around the texture plane).

**Comment by kmcurry** [comment]
Needs steps to recreate.

**Comment by katlandreth** [comment]
It happens so randomly I don't have steps :(  Haven't been able to notice a pattern.

**Comment by kmcurry** [comment]
This can be re-created, somewhat imprecisely, by right-clicking to bring up the browser's default context menu and letting go off the menu. It's likely that there is an action tied to `mouseup` that assumes the inverse action on  `mousedown`. 3Scape receives one but not the other and mayhem ensues.

**Comment by kmcurry** [comment]
I added `oncontextmen="return false"` to `canvas`. That _should_ fix the problem :grin:
