### ISSUE TITLE
Update deprecated

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#350]
`body-parser deprecated bodyParser: use individual json/urlencoded middlewares server.js:34:9
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:85:29
express-session deprecated undefined resave option; provide resave option server.js:42:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option server.js:42:9
Loaded the configuration for local
body-parser deprecated bodyParser: use individual json/urlencoded middlewares app/routes/auth/index.js:9:11`

**Comment by jperez757** [comment]
I'll look into this soon but I think since app.use(bodyParser()); has been deprecated the new way to use bodyParser is by doing 
app.use(bodyParser.urlencoded());
app.use(bodyParser.json());

or 

app.use(bodyParser.urlencoded({
  extended: true
}));
