### ISSUE TITLE
Context Menu Jumps to Corner of Screen

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#351]
Unexpected Behavior-
* Place an object on the canvas, and open its context menu
* Mouse over the buttons in the context menu, and the whole menu jumps to the upper right corner of the screen, with many of the buttons off screen entirely

Expected Behavior - 
* Place an object on the canvas and open its context menu
* Mouse over the buttons in the context menu, buttons remain anchored in a circle around the object

Video - https://www.dropbox.com/s/kisotaufj8rr8a9/ContextMenuMoving.mov?dl=0

**Comment by kmcurry** [comment]
I guess my fix to the other caused this one

**Comment by katlandreth** [comment]
Definitely just started happening today.

**Comment by kmcurry** [comment]
The is fixed enough. If you try really hard you can sometimes catch it up there just before it fades out.
