### ISSUE TITLE
Spawning a Shape Many Times In A Row Causes Multiple Selection

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#356]
Unexpected Behavior -
* Hitting a shape button a bunch of times in a row, really fast, spawns a bunch of shapes 
* Some of those shapes will have a yellow outline around them as though multiple shapes are selected at the same time 
* Clicking on one of the shapes will sometimes cause multiple shapes to be highlighted - it's not clear that all of them are actually selected since arrow keys only move the one that's clicked.

Expected Behavior -
* Clicking one shape selects just that shape unless it's part of a snapped group, or the user has used a multi-select option to explicitly select more than one shape

![screen shot 2015-03-06 at 1 21 07 pm](https://cloud.githubusercontent.com/assets/4040900/6531155/f2b4fe32-c404-11e4-920b-cc8cd2d4dd69.png)
![screen shot 2015-03-06 at 1 21 05 pm](https://cloud.githubusercontent.com/assets/4040900/6531160/fb97deb6-c404-11e4-8210-e60a79bf7d6f.png)

**Comment by kmcurry** [comment]
This wasn't intentionally fixed but seems to not be an issue. Could be a positive side-effect of general cleanup
