### ISSUE TITLE
Need Log Out Button in Menu 

### ISSUE THREAD

**Issue by katlandreth** [kmcurry/3Scape#360]
There should be a Log Out button in the drop down menu in the 3Scape creative area.  There should also be a Log Out button on the user's profile page.

**Comment by jperez757** [comment]
Do we have any specific image we want to use for the Log Out button on the create page?

**Comment by jperez757** [comment]
Never mind, I looked and found the library for Font Awesome icons. Currently it is set up with the sign-out icon which is formatted like the other icons used.

**Comment by jperez757** [comment]
I've pushed my changes for review.
Changes Made:

**Comment by jperez757** [comment]
I've pushed my changes to be reviewed.

Changes Made:
  - Added a Sign Out button to the Profile Page. It's justified to the far right. 
  - Added a Sign Out button to the Create Page drop down menu. It's the last option. 

Concerns: 
  - The Previous "Load Saved 3Scape" header could be pressed before I made changes but it didn't lead anywhere. ("#"). Was it supposed to redirect creators in the future?
  - The new "Load Saved 3Scape" header, when formatted like the others, fills up the entire width of the drop down menu. It looks a little off. Should we increase the width of the drop down menu, not use all caps for header formatting, change the header title, etc?

**Comment by jperez757** [comment]
![screen shot 2015-03-08 at 5 22 33 pm](https://cloud.githubusercontent.com/assets/10623892/6547762/05344040-c5b8-11e4-9772-f47964ea912d.png)

**Comment by kmcurry** [comment]
Perfect. Thanks!

On Sunday, March 8, 2015, jperez757 <notifications@github.com> wrote:

> [image: screen shot 2015-03-08 at 5 22 33 pm]
> <https://cloud.githubusercontent.com/assets/10623892/6547762/05344040-c5b8-11e4-9772-f47964ea912d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmcurry/3Scape/issues/360#issuecomment-77775322>.
>


-- 
Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me

**Comment by jperez757** [comment]
No problem! let me know when you're ready for a pull request.

**Comment by kmcurry** [comment]
Anytime

**Comment by jperez757** [comment]
I need you to make an iss360 branch?

**Comment by katlandreth** [comment]
If we move the "Go-To" section to the bottom, and add Sign Out as the last item in that list it would save some space and I think make for a logical grouping. What do y'all think?
