### ISSUE TITLE
Fix context menu when opening on a new object

### ISSUE THREAD

**Issue by soffos** [kmcurry/3Scape#385]
Steps to replicate:
* Create two objects
* Right click one of them to bring up the context menu
* Right click the second to witness the vanishing act

**Comment by jperez757** [comment]
Are you on the updated snappy branch? I can't replicate the issue.

**Comment by kmcurry** [comment]
I can replicate it. Please fix it if you can.

On Sun, Mar 22, 2015 at 7:42 PM, jperez757 <notifications@github.com> wrote:

> Are you on the updated snappy branch? I can't replicate the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmcurry/3Scape/issues/385#issuecomment-84733211>.
>



-- 
Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me
