### ISSUE TITLE
Possible Invisible Objects

### ISSUE THREAD

**Issue by jperez757** [kmcurry/3Scape#386]
While attempting to make a 5x5 square of block objects I realized that I couldn't finish the structure because something was causing some blocks to float. 
![screen shot 2015-03-22 at 9 01 06 pm](https://cloud.githubusercontent.com/assets/10623892/6772507/a4c7b082-d0d6-11e4-8804-d02b956aa5c4.png)

**Comment by kmcurry** [comment]
This is related to #349 and is due the fact that concave areas are not yet supported in collision detection. CC @mbrazell
