### ISSUE TITLE
Pipe Physics

### ISSUE THREAD

**Issue by jperez757** [kmcurry/3Scape#392]
Sometimes if you add a few straight pipes with an elbow on one end and then drop the object on the elbow section the pipe behaves very strangely, rocking around wildly. I'll try to get a  video of it at a later time.

**Comment by kmcurry** [comment]
Seems like it should rock if dropped on the elbow. There have been several iterations of physics and Parts since this was added. Also tubes and elbows have been removed until concave physics support can be added.
