### ISSUE TITLE
Objects Disappear Sometimes When Rescaling

### ISSUE THREAD

**Issue by jperez757** [kmcurry/3Scape#395]
I've witnessed two versions of this. Steps for version 1: 
- Create an object
- resize to 0%
- with context menu still up use either the right or left arrows on your keyboard
- attempt to resize to something viewable. 
- the object is gone

Version 2 only happens sometimes but it occurs when you scale an object to the max size rapidly. I've only attempted this with cubes.

**Comment by kmcurry** [comment]
The new resize prevents scale < .2
