### ISSUE TITLE
Color Changes Undo When Selecting Single Part of a Larger Object

### ISSUE THREAD

**Issue by jperez757** [kmcurry/3Scape#402]
Steps to recreate:
 * Snap 3 cubes together
 * Change the color of the snapped cubes to any color
 * Double click the center cube as if unsnapping
 * The other cubes revert back to the default purple

**Comment by jperez757** [comment]
If you change the color of one of the cubes before step 2 then completing the steps will result in the cube reverting back to the initial color you changed it to.

**Comment by jperez757** [comment]
I think this ties into #394

**Comment by kmcurry** [comment]
Just tried this and it seems to be fixed.
