### ISSUE TITLE
Top Heights Are Uneven

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#418]
![screen shot 2015-04-13 at 9 37 03 pm](https://cloud.githubusercontent.com/assets/69151/7128791/4eea4e8a-e225-11e4-98d4-aba44ed18687.png)

**Comment by katlandreth** [comment]
Thought I fixed this yesterday. Are you still seeing this after you merged my changes last night?

**Comment by kmcurry** [comment]
This was from latest, yes.
