### ISSUE TITLE
When a Part is in motion and the same Part is added the first Part stops moving

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#427]
1. Add the Wedge
2. Click on top of the Wedge and add a Sphere
3. While the Sphere is rolling click on the Wedge again and add another Sphere
4. The first Sphere stops moving

**Comment by kmcurry** [comment]
Possibly happens when adding things to PhysicsSimulator?

**Comment by mbrazell** [comment]
Checking it out.

**Comment by mbrazell** [comment]
Fixed, checked into Snappy.
