### ISSUE TITLE
Content: 3 Wedges

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#439]
Make a 3Scape that presents the lesson of the 3 Wedges:

* 3 Wedges of different sizes side-by-side in front of the Camera
* 3 Spheres at the tops of each of the Wedges
* A "button" in the 3Scape that sends the Spheres rolling down the Wedges simultaneously
* Includes BalloonTipLabels that describe what is being taught.

**Comment by katlandreth** [comment]
Neat idea. I'm on it.
